# Until https://github.com/julia-actions/julia-uploadcodecov/issues/1 get fixed
# submit coverage report via travis
language: julia
os:
  - linux
julia:
  - 1.0

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
