name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'   # oldest supported in Project.toml
          - '1'     # latest stable
          - 'nightly'
        os:
          - ubuntu-latest
        include:  # spare windows/macos CI credits
          - os: windows-latest
            version: '1'
          - os: macOS-latest
            version: '1'

    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1
      - name: Test XTermColors
        run: |
          julia --project -e 'using Pkg; Pkg.develop(url="https://github.com/JuliaImages/XTermColors.jl")'  # FIXME: remove when registered
          julia --project -e 'using Pkg; Pkg.test("XTermColors")'
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
