name: Unit test
on: [push, pull_request]

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.0'   # oldest supported in Project.toml
          - '1'     # latest stable
          - 'nightly'
        os:
          - ubuntu-latest
        include:  # spare windows/macos CI credits
          - os: windows-latest
            version: '1'
          - os: macOS-latest
            version: '1'

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - name: "Compat fix for Julia < v1.3.0"
        if: ${{ matrix.version == '1.0' }}
        run: |
          using Pkg
          Pkg.add([PackageSpec(name="AbstractFFTs", version="0.5")])
        shell: julia --project=. --startup=no --color=yes {0}
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts 
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1

      # Unless tokenless upload is enabled, we can only submit coverage via
      # environment variable. But PRs from other fork can't do that.
      # See issue: https://github.com/julia-actions/julia-uploadcodecov/issues/1
